[tool.poetry]
name = "pydantic-pandas"
version = "0.1.0"
description = ""
authors = ["Kaio Silva"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"
pydantic = "^2.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
